language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.1
    - android-29
    - extra-android-m2repository


script:
  - yes | sdkmanager --licenses
  - ./gradlew build